# Note 01

## 协程 (coroutine) 的特性

通过 `async`, `await` 来声明协程函数

```python
async def foo() -> None:
    print('foo')
    await asyncio.sleep(1)
```

这时 `foo()` 返回一个协程对象，并不会直接执行函数内的语句，有三种运行协程的机制（以上面的 `foo()` 为例）：

- `asyncio.run(foo())`
- 在一个协程里 `await foo()`
- 在一个协程里 `task = asyncio.create_task(foo())` 然后再 `await task` ，这时如果一起 `await` 了多个 task ，则这些 task 会被并发执行

> 可等待对象：能接在 `await` 后面的都算可等待对象，主要有三种： 协程 (coroutine) 、任务、期物 (future)

## 休眠

```python
await asyncio.sleep(1)
```

休眠 1 秒，只阻塞当前协程，不会对全局造成影响。可以带上 `result=` 参数，当休眠结束后 `asyncio.sleep` 会把这个参数返回回去

```python
r: str = await asyncio.sleep(1.0, result='foo')
```

`r` 将会是 `'foo'`

## 并发执行任务

```python
return_values = asyncio.gather(foo(), foo(), foo())
```

并发执行三个 `foo()` ，它们的返回值会分别被放进 `return_values` 里，有一个 `return_exceptions` 参数，默认为 `False` ，也就是说如果里面的某一个任务发生了异常，这个异常会立刻被 `asyncio.gather` 抛出，如果为 `True` 这个异常会被当作返回值放进 `return_values` 里

```python
for coroutine in asyncio.as_completed([foo(), foo(), foo()]):
    await coroutine
```

也是并发执行，但这样可以遍历每个协程的返回值

## 超时

```python
try:
    await asyncio.wait_for(foo(), timeout=1.0)
except asyncio.TimeoutError:
    print('timeout')
```

## 在另一个线程中执行

```python
def block(seconds: float, result: str) -> str:
    time.sleep(seconds)
    return result
```

这个不是协程函数，而且 `time.sleep` 会阻塞全局，可以在另一个线程里执行：

```python
r: str = await asyncio.to_thread(block, 1.0, 'foo')
rl = await asyncio.gather(foo(), foo())
```

这样 `block(1.0, 'foo)` 和两个 `foo()` 会被并发执行，而且互不阻塞


